### ISSUE TITLE
0.9.16-SNAPSHOT is missing

### ISSUE THREAD

**Issue by SeriousSem** [uklance/tapestry-cometd#58]
I just want to test a demo and get this error:

The POM for org.lazan:tapestry-cometd:jar:0.9.16-SNAPSHOT is missing, no dependency information available

 Failed to execute goal on project tapestry-cometd-demo: 
Could not resolve dependencies for project org.lazan:tapestry-cometd-demo:war:1.0-SNAPSHOT: Failure to find org.lazan:tapestry-cometd:jar:0.9.16-SNAPSHOT in https://github.com/uklance/releases/raw/master was cached in the local repository, resolution will not be reattempted until the update interval of uklance-github has elapsed or updates are forced -> [Help 1]

**Comment by uklance** [comment]
Snapshot versions are unreleased versions which can change from day to day and are only used whilst developing. You can see that the releases repo [here](https://github.com/uklance/releases) only has released versions (ie versions without "-SNAPSHOT" suffix.

Edit the pom.xml in tapestry-cometd-demo and change the version to the latest release version, currently 0.9.17.

**Comment by SeriousSem** [comment]
Oh, sorry for inconvenience. I did it. Thanks.
